// 07.vue/vue-learning/chap04_todolist/src/components/TodoList.vue

<template>
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th style="{width:'10%'}">ID</th>
                    <th>Todo</th>
                    <th style="{width:'10%'}">Complete</th>
                    <th style="{width:'10%'}">Delete</th>
                </tr>
            </thead>
            <tbody>
                <TodoListItem v-for="(todo, index) in todoList" 
                    :key="todo.id" :todo="todo" :index="index"
                    :updateTodo="updateTodo" :deleteTodo="deleteTodo"></TodoListItem>
            </tbody>
        </table>
    </div>
</template>

<script>
    import TodoListItem from './TodoListItem.vue'
    export default {
        props: ['todoList', "updateTodo", "deleteTodo"],
        components: { TodoListItem }
    }
</script>

<style scoped>

</style>

// 02.react/ReactLearning/chap02todolist/src/components/TodoList.js

import React from 'react'
import './css/todos.css';
import TodoListItem from './TodoListItem'

function Todolist(props){

    const {todoList, updataTodo, deleteTodo} = props;

    return (
        <div>
            <table className="table">
                <thead>
                    <tr>
                        <th style={{width:'10%'}}>ID</th>
                        <th>Todo</th>
                        <th style={{width:'10%'}}>Complete</th>
                        <th style={{width:'10%'}}>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {todoList.map(item => <TodoListItem 
                    todo={item} updateTodo={updataTodo} deleteTodo={deleteTodo} key={item.id}></TodoListItem>)}
                </tbody>
            </table>
        </div>
    )
}
export default Todolist;
